image: python:3.10-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .venv/

stages:
  - build
  - lint
  - test
  - publish
  - stop
  - deploy
  - cleanup

before_script:
  - apk add --no-cache git gcc musl-dev libffi-dev
  - python -m venv .venv
  - source .venv/bin/activate
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - echo "Build step here if needed"
  tags:
    - ezenplo-backend

lint:
  stage: lint
  script:
    - pre-commit run --all-files
  tags:
    - ezenplo-backend

unit-test:
  stage: test
  script:
    - pytest tests/
  tags:
    - ezenplo-backend

publish:
  stage: publish
  tags:
    - eZenplo
  script:
    - docker build -t $APP_NAME .
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker tag $APP_NAME:latest $DOCKER_REGISTRY/$APP_NAME:latest
    - docker push $DOCKER_REGISTRY/$APP_NAME:latest
  only:
    - main

stop:
  stage: stop
  tags:
    - eZenplo
  script:
    - docker-compose down
  only:
    - main

deploy:
  stage: deploy
  tags:
    - eZenplo
  script:
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker pull $DOCKER_REGISTRY/$APP_NAME:latest
    - docker-compose -f docker-compose-prod.yml up -d
  only:
    - main

cleanup:
  stage: cleanup
  tags:
    - eZenplo
  script:
    - docker system prune -f
  only:
    - main
