image: python:3.10-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .venv/

stages:
  - build
  - lint
  - test

before_script:
  - apk add --no-cache git gcc musl-dev libffi-dev
  - python -m venv .venv
  - source .venv/bin/activate
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - echo "Build step here if needed"
  tags:
    - ezenplo-backend

lint:
  stage: lint
  script:
    - pre-commit run --all-files
  tags:
    - ezenplo-backend

unit-test:
  stage: test
  script:
    - pytest tests/
  tags:
    - ezenplo-backend
