repos:
  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
    - id: isort
      args: [
        "-q",
        "--overwrite-in-place"
      ]

  - repo: https://github.com/psf/black
    rev: '23.7.0'
    hooks:
    - id: black
      args: [
        "--quiet"
      ]

  - repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'
    hooks:
    - id: flake8
      additional_dependencies:
        - "flake8-html"
      args: [
        "--extend-ignore=W0104,E501",
        "--exit-zero"
      ]

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.5'
    hooks:
    - id: bandit
      args: [
        "-r",
        "-o=bandit_report.txt",
        "-f=txt",
        "--exit-zero",
        "-q"
      ]

  - repo: local
    hooks:
      - id: static-check-autoflake
        name: Remove all unused code
        entry: autoflake --remove-all-unused-imports --ignore-init-module-imports --in-place
        language: python
        additional_dependencies: ['autoflake']

  - repo: https://github.com/PyCQA/pylint
    rev: "v3.0.2"
    hooks:
      - id: pylint
        args:
          [
            "--recursive=yes",
            "--persistent=yes",
            "--exit-zero",
          ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: pretty-format-json
        args: ["--autofix", "--indent=4", "--no-ensure-ascii"]

default_language_version:
  python: python3

