
CREATE TABLE ages.employee (
    id INT(10) NOT NULL AUTO_INCREMENT,
    user_id INT(10),
    name VARCHAR(70) NOT NULL,
    email VARCHAR(255) NOT NULL,
    city VARCHAR(100),
    street VARCHAR(150),
    complement VARCHAR(100),
    neighborhood VARCHAR(100),
    country VARCHAR(100),
    postal_code VARCHAR(20),
    gender CHAR(1) NOT NULL,
    civil_state VARCHAR(20) NOT NULL,
    birth_date DATE,
    admission_date DATE,
    height DECIMAL(5,2),
    weight DECIMAL(5,2),
    ethnicity VARCHAR(50),
    number_of_children INT(2),
    company VARCHAR(100),
    position VARCHAR(100),
    department VARCHAR(100),
    area VARCHAR(100),
    branch VARCHAR(100),
    salary_range VARCHAR(50),
    education_level VARCHAR(50),
    psychosocial_illnesses VARCHAR(255),
    number_of_promotions INT(2),
    number_of_warnings INT(2),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES user(id),
    UNIQUE KEY (email)
);